/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import bus.KhuyenMai_BUS;
import entities.KhuyenMai;

/**
 *
 * @author NguyenThanhLuan
 */
public class Form_DanhSachVoucher extends javax.swing.JFrame {
	private ArrayList<KhuyenMai> listVoucher;
	private DefaultTableModel tableModelVoucher;
	private KhuyenMai_BUS khuyenMai_BUS;
	private boolean checkImport = false;

    /**
     * Creates new form Form_DanhSachVoucher
     */
    public Form_DanhSachVoucher(ArrayList<KhuyenMai> listVoucher) {
        this.listVoucher = listVoucher;
        initComponents();
        loadVoucher();
        khuyenMai_BUS = new KhuyenMai_BUS();
        this.setLocationRelativeTo(null);
    }
    
    private void loadVoucher() {
    	for(KhuyenMai km : listVoucher) {
    		tableModelVoucher.addRow(new Object[] {km.getCodeKhuyenMai(),utilities.GetToDay.today(), km.getNgayKhuyenMai(), km.getNgayHetHanKM(), km.getLoaiKhuyenMai(), km.getDonHangTu(), km.getGiaTri(), (km.getSoLuotDaApDung() == 0) ? "Chưa sử dụng" : "Đã sử dụng"});
    	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ALL = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVoucher = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        importVoucher = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        back = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 600));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        ALL.setLayout(new java.awt.BorderLayout());
        ALL.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 145, 239));
        jLabel1.setText("Danh sách voucher");
        jPanel5.add(jLabel1);

        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        tableVoucher.setModel(tableModelVoucher = new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã giảm giá", "Ngày tạo", "Ngày kích hoạt", "Ngày hết hạn ", "Hình thức giảm","Đon hàng từ" ,"Mức giảm giá", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVoucherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVoucher);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        ALL.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(285, 58));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 14));

        importVoucher.setText("Import");
        importVoucher.setPreferredSize(new java.awt.Dimension(120, 30));
        importVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importVoucherActionPerformed(evt);
            }
        });
        jPanel2.add(importVoucher);
        jPanel2.add(filler2);

        back.setText("Trở về");
        back.setPreferredSize(new java.awt.Dimension(120, 30));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back);
        jPanel2.add(filler1);

        ALL.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon/icon-voucher.png"))); // NOI18N
        jPanel3.add(jLabel3);

        ALL.add(jPanel3, java.awt.BorderLayout.LINE_START);

        getContentPane().add(ALL, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importVoucherActionPerformed
        // TODO add your handling code here:
    	if(khuyenMai_BUS.xuatFile(listVoucher)) {
    		importVoucher.setEnabled(false);
    		checkImport = true;
    	}
    }//GEN-LAST:event_importVoucherActionPerformed

    private void tableVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVoucherMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableVoucherMouseClicked

	private void backActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backActionPerformed
		// TODO add your handling code here:
		int yes = JOptionPane.showConfirmDialog(this, "Bạn nên import voucher, bạn có chắc chắn muốn thoát !",
				"Thông báo", JOptionPane.YES_NO_OPTION);
		if (yes == JOptionPane.YES_OPTION) {
			this.setVisible(false);
			this.dispose();
		} else {
			setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
		}
	}// GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ALL;
    private javax.swing.JButton back;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton importVoucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVoucher;
    // End of variables declaration//GEN-END:variables
}
