/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

import bus.ChiTietKhuyenMai_BUS;
import bus.KhuyenMai_BUS;
import entities.ChiTietKhuyenMai;
import entities.KhuyenMai;
import entities.SanPham;
import utilities.GetToDay;

import java.awt.Color;
import java.sql.Date;

/**
 *
 * @author NguyenThanhLuan
 */
public class Form_XemChiTietKhuyeMai extends javax.swing.JFrame {
	private DefaultTableModel tableModel;
	private ArrayList<ChiTietKhuyenMai> danhSachCT;
	private ChiTietKhuyenMai_BUS chiTietKhuyenMai_BUS;
	private KhuyenMai_BUS khuyenMai_BUS;
	private ArrayList<KhuyenMai> khuyenMais;
	private ArrayList<ChiTietKhuyenMai> chiTietKhuyenMais;
	private ArrayList<SanPham> sanPhams;
	private static String maKM;
	
	
	private void loadData() {
		lblMaKM.setText(khuyenMais.get(0).getCodeKhuyenMai());
		lblTenKM.setText(khuyenMais.get(0).getTenKhuyenMai());
		Date ngayTao = chiTietKhuyenMai_BUS.getNgayTao(maKM);
		int stt = 1;
		for(SanPham sp : sanPhams) {
			tableModel.addRow(new Object[] {stt++,sp.getSanPhamID(), sp.getTenSanPham(), utilities.GetToDay.sdf.format(ngayTao)});
		}
	}
	
    /**
     * Creates new form GUI_XemChiTietKhuyeMai
     */
    public Form_XemChiTietKhuyeMai(String maKM) {
    	this.maKM = maKM;
        initComponents();
    	chiTietKhuyenMai_BUS = new ChiTietKhuyenMai_BUS();
    	sanPhams = chiTietKhuyenMai_BUS.laySanPhamKMTheoMa(maKM);
    	khuyenMais = chiTietKhuyenMai_BUS.layKhuyenMaiTheoMa(maKM);
    	chiTietKhuyenMais = chiTietKhuyenMai_BUS.layCTTKMTheoMa(maKM);

        loadData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChiTietSanPham = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMaKM = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTenKM = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tableChiTietSanPham.setModel(tableModel = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm ", "Tên sản phẩm", "Ngày tạo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableChiTietSanPham);
        if (tableChiTietSanPham.getColumnModel().getColumnCount() > 0) {
            tableChiTietSanPham.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setMaximumSize(new java.awt.Dimension(100, 60));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(14, 102, 165));
        jLabel1.setText("Mã khuyến mãi:");
        jPanel4.add(jLabel1);

        lblMaKM.setText("AAA");
        jPanel4.add(lblMaKM);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(14, 102, 165));
        jLabel2.setText("Tên khuyến mãi: ");
        jPanel5.add(jLabel2);

        lblTenKM.setText("AAAA");
        jPanel5.add(lblTenKM);

        jPanel2.add(jPanel5);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setPreferredSize(new java.awt.Dimension(130, 50));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 13));

        back.setBackground(new java.awt.Color(255, 153, 153));
        back.setText("Trở về");
        back.setPreferredSize(new java.awt.Dimension(120, 30));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed
    
    public void loadDuLieu() {
    	tableChiTietSanPham.removeAll();
    	tableChiTietSanPham.setRowSelectionAllowed(false);
    	tableModel.setRowCount(0);
    	danhSachCT = new ArrayList<>();
    	danhSachCT = chiTietKhuyenMai_BUS.getAllChiTietKhuyenMai();
    	int stt = 1;
    	for(ChiTietKhuyenMai ctkm : danhSachCT) {
    		tableModel.addRow(new Object[] {stt++,ctkm.getSanPham().getSanPhamID(), ctkm.getKhuyenMai().getCodeKhuyenMai(), ctkm.getKhuyenMai().getCodeKhuyenMai(),ctkm.getKhuyenMai().getCodeKhuyenMai(), ctkm.getNgayTao()});
    	}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaKM;
    private javax.swing.JLabel lblTenKM;
    private javax.swing.JTable tableChiTietSanPham;
    // End of variables declaration//GEN-END:variables
}
