/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import bus.NhaCungCap_BUS;
import bus.NhaXuatBan_BUS;
import bus.SanPham_BUS;
import bus.ThuongHieu_BUS;
import connectDB.ConnectDB;
import dao.SanPham_DAO;
import entities.DanhMuc;
import entities.NhaCungCap;
import entities.NhaXuatBan;
import entities.SanPham;
import entities.TacGia;
import entities.TheLoai;
import entities.ThuongHieu;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import utilities.ImageProcessing;
import java.sql.Date;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;

/**
 *
 * @author ASUS
 */
public class TAB_ThemSanPhamKhac extends javax.swing.JFrame {

    /**
     * Creates new form TAB_ThemSanPham
     */
    ArrayList<String> th_name;
    ArrayList<String> ncc_name;

    public TAB_ThemSanPhamKhac() {
        initComponents();
        ConnectDB.getInstance().connect();

        this.txtNgay.setDate(java.util.Calendar.getInstance().getTime());

        th_name = new ArrayList<String>();
        ncc_name = new ArrayList<String>();

        NhaCungCap_BUS nhaCungCap_BUS = new NhaCungCap_BUS();
        ArrayList<NhaCungCap> list_NCC = nhaCungCap_BUS.getAllNhaCungCap();
        for (NhaCungCap ncc : list_NCC) {
            ncc_name.add(ncc.getTenNhaCungCap());
        }

        ThuongHieu_BUS thuongHieu_BUS = new ThuongHieu_BUS();
        ArrayList<ThuongHieu> list_TH = thuongHieu_BUS.getAllThuongHieu();
        for (ThuongHieu th : list_TH) {
            th_name.add(th.getTenThuongHieu());
        }

        for (String string : ncc_name) {
            comboBox_NCC.addItem(string);
        }

        for (String string : th_name) {
            comboBox_TH.addItem(string);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        filler37 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 50), new java.awt.Dimension(10, 10));
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        filler25 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(30, 60), new java.awt.Dimension(10, 10));
        jPanel14 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        filler28 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(30, 20), new java.awt.Dimension(10, 10));
        filler29 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(20, 10), new java.awt.Dimension(10, 10));
        jLabel_Img = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        filler27 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jPanel19 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        filler30 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(30, 50), new java.awt.Dimension(10, 10));
        filler26 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 10));
        jPanel32 = new javax.swing.JPanel();
        jLabel_Barcode = new javax.swing.JLabel();
        jTextField_Barcode = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 25), new java.awt.Dimension(10, 10));
        jPanel44 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_TenSanPham = new javax.swing.JTextField();
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 25), new java.awt.Dimension(10, 10));
        jPanel45 = new javax.swing.JPanel();
        jLabel_SoLuongTon = new javax.swing.JLabel();
        jTextField_SoLuongTon = new javax.swing.JTextField();
        filler24 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 25), new java.awt.Dimension(10, 10));
        jPanel38 = new javax.swing.JPanel();
        jLabel_Thue1 = new javax.swing.JLabel();
        jTextField_Thue = new javax.swing.JTextField();
        filler35 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(30, 60), new java.awt.Dimension(10, 10));
        jPanel22 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel_GiaNhap = new javax.swing.JLabel();
        jTextField_GiaNhap = new javax.swing.JTextField();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 25), new java.awt.Dimension(10, 10));
        jPanel33 = new javax.swing.JPanel();
        jLabel_NhaCungCap = new javax.swing.JLabel();
        jTextField_NhaCungCap = new javax.swing.JTextField();
        jPanel_CBB_NhaCungCap = new javax.swing.JPanel();
        comboBox_NCC = new javax.swing.JComboBox<>();
        jPanel55 = new javax.swing.JPanel();
        jLabel_TacGia = new javax.swing.JLabel();
        jTextField_ThuongHieu = new javax.swing.JTextField();
        jPanel_CBB_ThuongHieu = new javax.swing.JPanel();
        comboBox_TH = new javax.swing.JComboBox<>();
        jPanel58 = new javax.swing.JPanel();
        jLabel_SoTrang2 = new javax.swing.JLabel();
        jComboBox_LoaiDoiTra = new javax.swing.JComboBox<>();
        filler22 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 25), new java.awt.Dimension(10, 10));
        jPanel39 = new javax.swing.JPanel();
        jLabel_NgayNhap1 = new javax.swing.JLabel();
        txtNgay = new com.toedter.calendar.JDateChooser();
        filler31 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(30, 60), new java.awt.Dimension(10, 10));
        jPanel1 = new javax.swing.JPanel();
        filler32 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(30, 60), new java.awt.Dimension(10, 10));
        jPanel23 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        filler33 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(50, 50), new java.awt.Dimension(50, 50));
        jPanel46 = new javax.swing.JPanel();
        jLabel_NamSanXuat = new javax.swing.JLabel();
        jTextField1_NamSanXuat = new javax.swing.JTextField();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 20), new java.awt.Dimension(10, 10));
        jPanel50 = new javax.swing.JPanel();
        jLabel_XuatXu = new javax.swing.JLabel();
        jTextField_XuatXu = new javax.swing.JTextField();
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 20), new java.awt.Dimension(10, 10));
        jPanel26 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        filler40 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 70), new java.awt.Dimension(10, 10));
        jButton_Luu = new javax.swing.JButton();
        filler43 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jButton_Sua = new javax.swing.JButton();
        filler45 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jButton_Huy = new javax.swing.JButton();
        filler41 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 70), new java.awt.Dimension(10, 10));
        filler34 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(30, 60), new java.awt.Dimension(10, 10));
        jPanel3 = new javax.swing.JPanel();
        jLabel_Warning = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 15), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 680));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1119, 100));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(filler37);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(15, 145, 239));
        jLabel3.setText("Thông tin sản phẩm");
        jPanel2.add(jLabel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));
        jPanel9.add(filler25);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(300, 780));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.Y_AXIS));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel18.setPreferredSize(new java.awt.Dimension(250, 175));
        jPanel18.setLayout(new javax.swing.BoxLayout(jPanel18, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(350, 300));
        jPanel6.setMinimumSize(new java.awt.Dimension(70, 150));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 165));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(filler28, java.awt.BorderLayout.LINE_END);
        jPanel6.add(filler29, java.awt.BorderLayout.LINE_START);

        jLabel_Img.setBackground(new java.awt.Color(255, 204, 204));
        jLabel_Img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Img.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel_Img.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_Img.setMaximumSize(new java.awt.Dimension(50, 190));
        jLabel_Img.setMinimumSize(new java.awt.Dimension(50, 190));
        jLabel_Img.setPreferredSize(new java.awt.Dimension(40, 190));
        jPanel6.add(jLabel_Img, java.awt.BorderLayout.CENTER);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(15, 145, 239));
        jLabel6.setText("Thông tin chung");
        jPanel11.add(jLabel6);
        jPanel11.add(filler27);

        jPanel6.add(jPanel11, java.awt.BorderLayout.PAGE_START);

        jPanel18.add(jPanel6);

        jPanel14.add(jPanel18);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setMinimumSize(new java.awt.Dimension(82, 30));
        jPanel19.setPreferredSize(new java.awt.Dimension(304, 40));
        jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.X_AXIS));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(135, 45));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel19.add(jPanel7);

        jButton4.setBackground(new java.awt.Color(15, 145, 239));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Chọn");
        jButton4.setMaximumSize(new java.awt.Dimension(72, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton4);
        jPanel19.add(filler30);

        jPanel14.add(jPanel19);
        jPanel14.add(filler26);

        jPanel32.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel_Barcode.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Barcode.setText("Barcode");
        jLabel_Barcode.setPreferredSize(new java.awt.Dimension(74, 10));
        jPanel32.add(jLabel_Barcode, java.awt.BorderLayout.CENTER);

        jTextField_Barcode.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_Barcode.setPreferredSize(new java.awt.Dimension(71, 35));
        jTextField_Barcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_BarcodeFocusLost(evt);
            }
        });
        jTextField_Barcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_BarcodeMouseClicked(evt);
            }
        });
        jTextField_Barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_BarcodeActionPerformed(evt);
            }
        });
        jPanel32.add(jTextField_Barcode, java.awt.BorderLayout.PAGE_END);

        jPanel14.add(jPanel32);
        jPanel14.add(filler7);

        jPanel44.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel44.setLayout(new java.awt.BorderLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tên sản phẩm");
        jLabel11.setPreferredSize(new java.awt.Dimension(74, 10));
        jPanel44.add(jLabel11, java.awt.BorderLayout.CENTER);

        jTextField_TenSanPham.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_TenSanPham.setPreferredSize(new java.awt.Dimension(71, 35));
        jTextField_TenSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_TenSanPhamMouseClicked(evt);
            }
        });
        jTextField_TenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TenSanPhamActionPerformed(evt);
            }
        });
        jPanel44.add(jTextField_TenSanPham, java.awt.BorderLayout.PAGE_END);

        jPanel14.add(jPanel44);
        jPanel14.add(filler23);

        jPanel45.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel45.setLayout(new java.awt.BorderLayout());

        jLabel_SoLuongTon.setText("Số lượng tồn");
        jLabel_SoLuongTon.setPreferredSize(new java.awt.Dimension(74, 10));
        jPanel45.add(jLabel_SoLuongTon, java.awt.BorderLayout.CENTER);

        jTextField_SoLuongTon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_SoLuongTon.setPreferredSize(new java.awt.Dimension(71, 35));
        jTextField_SoLuongTon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_SoLuongTonMouseClicked(evt);
            }
        });
        jTextField_SoLuongTon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SoLuongTonActionPerformed(evt);
            }
        });
        jPanel45.add(jTextField_SoLuongTon, java.awt.BorderLayout.PAGE_END);

        jPanel14.add(jPanel45);
        jPanel14.add(filler24);

        jPanel38.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel38.setLayout(new java.awt.BorderLayout());

        jLabel_Thue1.setText("Thuế");
        jLabel_Thue1.setPreferredSize(new java.awt.Dimension(74, 10));
        jPanel38.add(jLabel_Thue1, java.awt.BorderLayout.CENTER);

        jTextField_Thue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_Thue.setPreferredSize(new java.awt.Dimension(71, 35));
        jTextField_Thue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_ThueMouseClicked(evt);
            }
        });
        jTextField_Thue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ThueActionPerformed(evt);
            }
        });
        jPanel38.add(jTextField_Thue, java.awt.BorderLayout.PAGE_END);

        jPanel14.add(jPanel38);

        jPanel9.add(jPanel14);
        jPanel9.add(filler35);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setMaximumSize(new java.awt.Dimension(300, 780));
        jPanel22.setMinimumSize(new java.awt.Dimension(120, 227));
        jPanel22.setPreferredSize(new java.awt.Dimension(300, 780));
        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(223, 120));
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel22.add(jPanel4);

        jPanel34.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel34.setLayout(new java.awt.BorderLayout());

        jLabel_GiaNhap.setText("Giá nhập");
        jLabel_GiaNhap.setPreferredSize(new java.awt.Dimension(74, 10));
        jPanel34.add(jLabel_GiaNhap, java.awt.BorderLayout.CENTER);

        jTextField_GiaNhap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_GiaNhap.setPreferredSize(new java.awt.Dimension(71, 35));
        jTextField_GiaNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_GiaNhapMouseClicked(evt);
            }
        });
        jTextField_GiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GiaNhapActionPerformed(evt);
            }
        });
        jPanel34.add(jTextField_GiaNhap, java.awt.BorderLayout.PAGE_END);

        jPanel22.add(jPanel34);
        jPanel22.add(filler14);

        jPanel33.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel33.setLayout(new java.awt.BorderLayout());

        jLabel_NhaCungCap.setText("Nhà cung cấp");
        jLabel_NhaCungCap.setPreferredSize(new java.awt.Dimension(74, 10));
        jPanel33.add(jLabel_NhaCungCap, java.awt.BorderLayout.CENTER);

        jTextField_NhaCungCap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_NhaCungCap.setPreferredSize(new java.awt.Dimension(71, 35));
        jTextField_NhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_NhaCungCapMouseClicked(evt);
            }
        });
        jTextField_NhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NhaCungCapActionPerformed(evt);
            }
        });
        jPanel33.add(jTextField_NhaCungCap, java.awt.BorderLayout.PAGE_END);

        jPanel22.add(jPanel33);

        jPanel_CBB_NhaCungCap.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_CBB_NhaCungCap.setMaximumSize(new java.awt.Dimension(250, 0));
        jPanel_CBB_NhaCungCap.setMinimumSize(new java.awt.Dimension(80, 0));
        jPanel_CBB_NhaCungCap.setPreferredSize(new java.awt.Dimension(221, 25));
        jPanel_CBB_NhaCungCap.setLayout(new javax.swing.BoxLayout(jPanel_CBB_NhaCungCap, javax.swing.BoxLayout.LINE_AXIS));

        comboBox_NCC.setMaximumSize(new java.awt.Dimension(32767, 0));
        comboBox_NCC.setMinimumSize(new java.awt.Dimension(72, 0));
        comboBox_NCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_NCCActionPerformed(evt);
            }
        });
        jPanel_CBB_NhaCungCap.add(comboBox_NCC);

        jPanel22.add(jPanel_CBB_NhaCungCap);

        jPanel55.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel55.setLayout(new java.awt.BorderLayout());

        jLabel_TacGia.setText("Thương hiệu");
        jLabel_TacGia.setPreferredSize(new java.awt.Dimension(74, 10));
        jPanel55.add(jLabel_TacGia, java.awt.BorderLayout.CENTER);

        jTextField_ThuongHieu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_ThuongHieu.setPreferredSize(new java.awt.Dimension(71, 35));
        jTextField_ThuongHieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_ThuongHieuMouseClicked(evt);
            }
        });
        jTextField_ThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ThuongHieuActionPerformed(evt);
            }
        });
        jPanel55.add(jTextField_ThuongHieu, java.awt.BorderLayout.PAGE_END);

        jPanel22.add(jPanel55);

        jPanel_CBB_ThuongHieu.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_CBB_ThuongHieu.setMaximumSize(new java.awt.Dimension(250, 0));
        jPanel_CBB_ThuongHieu.setMinimumSize(new java.awt.Dimension(80, 0));
        jPanel_CBB_ThuongHieu.setPreferredSize(new java.awt.Dimension(221, 25));
        jPanel_CBB_ThuongHieu.setLayout(new javax.swing.BoxLayout(jPanel_CBB_ThuongHieu, javax.swing.BoxLayout.LINE_AXIS));

        comboBox_TH.setMaximumSize(new java.awt.Dimension(32767, 0));
        comboBox_TH.setMinimumSize(new java.awt.Dimension(72, 0));
        comboBox_TH.setPreferredSize(new java.awt.Dimension(72, 0));
        comboBox_TH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_THActionPerformed(evt);
            }
        });
        jPanel_CBB_ThuongHieu.add(comboBox_TH);

        jPanel22.add(jPanel_CBB_ThuongHieu);

        jPanel58.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel58.setLayout(new java.awt.BorderLayout());

        jLabel_SoTrang2.setText("Loại đổi trả");
        jLabel_SoTrang2.setPreferredSize(new java.awt.Dimension(74, 10));
        jPanel58.add(jLabel_SoTrang2, java.awt.BorderLayout.CENTER);

        jComboBox_LoaiDoiTra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Được đổi trả", "Không được đổi" }));
        jComboBox_LoaiDoiTra.setMinimumSize(new java.awt.Dimension(72, 35));
        jComboBox_LoaiDoiTra.setPreferredSize(new java.awt.Dimension(119, 35));
        jPanel58.add(jComboBox_LoaiDoiTra, java.awt.BorderLayout.PAGE_END);

        jPanel22.add(jPanel58);
        jPanel22.add(filler22);

        jPanel39.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel39.setLayout(new java.awt.BorderLayout());

        jLabel_NgayNhap1.setText("Ngày nhập");
        jLabel_NgayNhap1.setPreferredSize(new java.awt.Dimension(74, 10));
        jPanel39.add(jLabel_NgayNhap1, java.awt.BorderLayout.CENTER);

        txtNgay.setPreferredSize(new java.awt.Dimension(88, 35));
        txtNgay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayMouseClicked(evt);
            }
        });
        jPanel39.add(txtNgay, java.awt.BorderLayout.PAGE_END);

        jPanel22.add(jPanel39);

        jPanel9.add(jPanel22);
        jPanel9.add(filler31);

        jPanel1.setBackground(new java.awt.Color(15, 145, 239));
        jPanel1.setPreferredSize(new java.awt.Dimension(3, 488));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel1);
        jPanel9.add(filler32);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setMaximumSize(new java.awt.Dimension(300, 780));
        jPanel23.setMinimumSize(new java.awt.Dimension(120, 227));
        jPanel23.setPreferredSize(new java.awt.Dimension(300, 780));
        jPanel23.setLayout(new javax.swing.BoxLayout(jPanel23, javax.swing.BoxLayout.Y_AXIS));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(223, 120));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(15, 145, 239));
        jLabel7.setText("Thông tin khác");
        jPanel8.add(jLabel7, java.awt.BorderLayout.CENTER);
        jPanel8.add(filler33, java.awt.BorderLayout.PAGE_END);

        jPanel23.add(jPanel8);

        jPanel46.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel46.setLayout(new java.awt.BorderLayout());

        jLabel_NamSanXuat.setText("Năm sản xuất");
        jLabel_NamSanXuat.setPreferredSize(new java.awt.Dimension(74, 10));
        jPanel46.add(jLabel_NamSanXuat, java.awt.BorderLayout.CENTER);

        jTextField1_NamSanXuat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1_NamSanXuat.setPreferredSize(new java.awt.Dimension(71, 35));
        jTextField1_NamSanXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_NamSanXuatActionPerformed(evt);
            }
        });
        jPanel46.add(jTextField1_NamSanXuat, java.awt.BorderLayout.PAGE_END);

        jPanel23.add(jPanel46);
        jPanel23.add(filler19);

        jPanel50.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel50.setLayout(new java.awt.BorderLayout());

        jLabel_XuatXu.setText("Xuất xứ");
        jLabel_XuatXu.setPreferredSize(new java.awt.Dimension(74, 10));
        jPanel50.add(jLabel_XuatXu, java.awt.BorderLayout.CENTER);

        jTextField_XuatXu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField_XuatXu.setPreferredSize(new java.awt.Dimension(71, 35));
        jTextField_XuatXu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_XuatXuActionPerformed(evt);
            }
        });
        jPanel50.add(jTextField_XuatXu, java.awt.BorderLayout.PAGE_END);

        jPanel23.add(jPanel50);
        jPanel23.add(filler21);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setPreferredSize(new java.awt.Dimension(200, 250));
        jPanel26.setLayout(new javax.swing.BoxLayout(jPanel26, javax.swing.BoxLayout.Y_AXIS));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel10.setPreferredSize(new java.awt.Dimension(0, 200));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));
        jPanel10.add(filler40);

        jButton_Luu.setBackground(new java.awt.Color(15, 145, 239));
        jButton_Luu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Luu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Luu.setText("Lưu");
        jButton_Luu.setMaximumSize(new java.awt.Dimension(200, 23));
        jButton_Luu.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });
        jPanel10.add(jButton_Luu);
        jPanel10.add(filler43);

        jButton_Sua.setBackground(new java.awt.Color(15, 145, 239));
        jButton_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sua.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Sua.setText("Sửa");
        jButton_Sua.setMaximumSize(new java.awt.Dimension(200, 23));
        jButton_Sua.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });
        jPanel10.add(jButton_Sua);
        jPanel10.add(filler45);

        jButton_Huy.setBackground(new java.awt.Color(15, 145, 239));
        jButton_Huy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Huy.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Huy.setText("Hủy");
        jButton_Huy.setMaximumSize(new java.awt.Dimension(200, 23));
        jButton_Huy.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HuyActionPerformed(evt);
            }
        });
        jPanel10.add(jButton_Huy);
        jPanel10.add(filler41);

        jPanel26.add(jPanel10);

        jPanel23.add(jPanel26);

        jPanel9.add(jPanel23);
        jPanel9.add(filler34);

        getContentPane().add(jPanel9);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1119, 100));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel_Warning.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel_Warning.setForeground(java.awt.Color.red);
        jPanel3.add(jLabel_Warning, java.awt.BorderLayout.CENTER);
        jPanel3.add(filler2, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_BarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_BarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_BarcodeActionPerformed

    private void jTextField_NhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NhaCungCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NhaCungCapActionPerformed

    private void jTextField_GiaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GiaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GiaNhapActionPerformed

    private void jTextField_TenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TenSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TenSanPhamActionPerformed

    private void jTextField_SoLuongTonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SoLuongTonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SoLuongTonActionPerformed

    private void jTextField1_NamSanXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_NamSanXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_NamSanXuatActionPerformed

    private void jTextField_XuatXuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_XuatXuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_XuatXuActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser;
        BufferedImage img = null;
        chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        file = chooser.getSelectedFile();
        try {
            img = ImageIO.read(file);
        } catch (Exception e) {
            e.printStackTrace();
        }

        Image newimg = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way        
        ImageIcon icon = new ImageIcon(newimg);
        jLabel_Img.setIcon(icon);


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField_ThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ThueActionPerformed

    public boolean check_empty() {

        if (this.jTextField_TenSanPham.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập tên của sản phẩm!");
            jTextField_TenSanPham.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_TenSanPham.setToolTipText("Tên của sản phẩm");
            return false;
        }
        if (this.jTextField_Barcode.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập barcode của sản phẩm!");
            jTextField_Barcode.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_Barcode.setToolTipText("Barcode của sản phẩm");
            return false;
        }
        if (this.jTextField_SoLuongTon.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập số lượng của sản phẩm!");
            jTextField_SoLuongTon.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_SoLuongTon.setToolTipText("Số lượng tồn của sản phẩm");
            return false;
        }
        try {
            int soLuongTon = Integer.parseInt(this.jTextField_SoLuongTon.getText());
            if (soLuongTon < 0) {
                jTextField_SoLuongTon.setBorder(BorderFactory.createLineBorder(Color.red));
                this.jLabel_Warning.setText("Số lượng tồn của sản phẩm phải là số nguyên dương!");
                return false;
            }
        } catch (Exception e) {
            jTextField_SoLuongTon.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jLabel_Warning.setText("Số lượng tồn của sản phẩm phải là số nguyên dương!");
            return false;
        }
        if (this.jTextField_NhaCungCap.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập tên nhà cung cấp!");
            jTextField_NhaCungCap.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_NhaCungCap.setToolTipText("Tên của nhà cung cấp");
            return false;
        }
        if (this.jTextField_GiaNhap.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập giá nhập hàng của sản phẩm!");
            jTextField_GiaNhap.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_GiaNhap.setToolTipText("Giá nhập của sản phẩm");
            return false;
        }
        try {
            double giaNhap = Double.parseDouble(this.jTextField_GiaNhap.getText());
            if (giaNhap < 0) {
                jTextField_GiaNhap.setBorder(BorderFactory.createLineBorder(Color.red));
                this.jLabel_Warning.setText("Giá nhập của sản phẩm phải là số thực > 0!");
                return false;
            }
        } catch (Exception e) {
            jTextField_GiaNhap.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jLabel_Warning.setText("Giá nhập của sản phẩm phải là số thực > 0!");
            return false;
        }
        if (this.jTextField_ThuongHieu.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập thương hiệu hàng của sản phẩm!");
            jTextField_ThuongHieu.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_ThuongHieu.setToolTipText("Giá nhập của sản phẩm");
            return false;
        }
        if (this.jTextField_Thue.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập thêm thuế của sản phẩm!");
            jTextField_Thue.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_Thue.setToolTipText("Thuế của sản phẩm");
            return false;
        }
        try {
            double thue = Double.parseDouble(this.jTextField_Thue.getText());
            if (thue < 0) {
                jTextField_Thue.setBorder(BorderFactory.createLineBorder(Color.red));
                this.jLabel_Warning.setText("Thuế của sản phẩm phải là số thực > 0!");
                return false;
            }
        } catch (Exception e) {
            jTextField_Thue.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jLabel_Warning.setText("Thuế của sản phẩm phải là số thực > 0!");
            return false;
        }

        if (this.txtNgay.getDate().toString().equals("")) {
            this.jLabel_Warning.setText("Hãy bổ sung ngày nhập");
            txtNgay.setBorder(BorderFactory.createLineBorder(Color.red));
            this.txtNgay.setToolTipText("Tên của sản phẩm");
            return false;
        }

        return true;
    }
    private void jButton_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LuuActionPerformed
        try {
            if (!check_empty()) {
                return;
            }
            SanPham sanPham = getNewSanPham();
            sanPham.setTinhTrang("CON_HANG");
            sanPham.setLoaiSanPham("SAN_PHAM_KHAC");
            SanPham_BUS sanPham_BUS = new SanPham_BUS();
            try {
                ConnectDB.getInstance().connect();
            } catch (Exception e) {
                e.printStackTrace();
            }
            System.out.println(sanPham);
            sanPham_BUS.addSanPham(sanPham);

            this.setVisible(false);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton_LuuActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        // TODO add your handling code here:
        try {
            if (!check_empty()) {
                return;
            }
            SanPham_BUS sanPham_BUS = new SanPham_BUS();
            try {
                ConnectDB.getInstance().connect();
            } catch (Exception e) {
                e.printStackTrace();
            }
            int decided = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn thay đổi lại sản phẩm này không?");
            if (decided == 0) {
                SanPham sanPham = getNewSanPham();
                sanPham.setSanPhamID(ID);
                sanPham_BUS.editSanPham(sanPham);
                this.setVisible(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HuyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton_HuyActionPerformed

    private void jTextField_TenSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_TenSanPhamMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_TenSanPhamMouseClicked

    private void jTextField_BarcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_BarcodeMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_BarcodeMouseClicked

    private void jTextField_SoLuongTonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_SoLuongTonMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_SoLuongTonMouseClicked

    private void jTextField_NhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_NhaCungCapMouseClicked
        this.jLabel_Warning.setText("");
        comboBox_NCC.setPopupVisible(true);
        comboBox_NCC.setSelectedIndex(-1);
           
    }//GEN-LAST:event_jTextField_NhaCungCapMouseClicked

    private void jTextField_GiaNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_GiaNhapMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_GiaNhapMouseClicked

    private void jTextField_ThuongHieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_ThuongHieuMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
        comboBox_TH.setPopupVisible(true);
        comboBox_TH.setSelectedIndex(-1);
          
    }//GEN-LAST:event_jTextField_ThuongHieuMouseClicked

    private void txtNgayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_txtNgayMouseClicked

    private void jTextField_ThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_ThueMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_ThueMouseClicked

    private void comboBox_NCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_NCCActionPerformed
        // TODO add your handling code here:
        if (comboBox_NCC.getSelectedIndex() != -1) {
            jTextField_NhaCungCap.setText(comboBox_NCC.getSelectedItem() + "");
            comboBox_NCC.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_comboBox_NCCActionPerformed

    private void jTextField_ThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ThuongHieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ThuongHieuActionPerformed

    private void comboBox_THActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_THActionPerformed
        // TODO add your handling code here:
        if (comboBox_TH.getSelectedIndex() != -1) {
            jTextField_ThuongHieu.setText(comboBox_TH.getSelectedItem() + "");
            comboBox_TH.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_comboBox_THActionPerformed

    private void jTextField_BarcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_BarcodeFocusLost
        // TODO add your handling code here:
        if (!jTextField_Barcode.getText().trim().equals("")) {
            SanPham_BUS sanPham_BUS = new SanPham_BUS();
            SanPham sp = sanPham_BUS.getChiMotSanPhamTheoMaHoacBarcode(this.jTextField_Barcode.getText());
            if (sp != null) {
                if (sp.getLoaiSanPham().equals("SAN_PHAM_KHAC")) {
                    this.setSanPhamSach(sp);

                    this.disVisibleForSua();
                } else {
                    JOptionPane.showMessageDialog(null, "Sản phẩm này có barcode đã tồn tại");
                    this.jTextField_Barcode.setText("");
                }

            }
        }
    }//GEN-LAST:event_jTextField_BarcodeFocusLost

    public SanPham getNewSanPham() {
        String tenSanPham = jTextField_TenSanPham.getText();
        int soLuongTon = Integer.parseInt(jTextField_SoLuongTon.getText());
        String barcode = jTextField_Barcode.getText();
        double giaNhap = Double.parseDouble(jTextField_GiaNhap.getText());

        double thue = Double.parseDouble(jTextField_Thue.getText().trim())*100;
        int namSanXuat;
        try {
            namSanXuat = Integer.parseInt(jTextField1_NamSanXuat.getText());
        } catch (Exception e) {
            namSanXuat = 1;
        }
        String tenNhaCungCap = jTextField_NhaCungCap.getText();
        String tenThuongHieu = jTextField_ThuongHieu.getText();
        String xuatXu;
        try {
            xuatXu = jTextField_XuatXu.getText();
        } catch (Exception e) {
            xuatXu = "";
        }
        String loaiDoiTra = jComboBox_LoaiDoiTra.getSelectedItem().toString();

        SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
        String date = dcn.format(txtNgay.getDate());
        Date DATE = Date.valueOf(date);

        String partialPath;
        try {
            String filePath = this.file.getPath();
            partialPath = filePath.substring(filePath.indexOf("img\\products"));
        } catch (Exception e) {
            partialPath = "";
        }

        ThuongHieu th = new ThuongHieu();
        NhaCungCap ncc = new NhaCungCap();

        try {
            th.setTenThuongHieu(tenThuongHieu);
            ncc.setTenNhaCungCap(tenNhaCungCap);
        } catch (Exception e) {

            e.printStackTrace();
        }

        SanPham_BUS sanPham_BUS = new SanPham_BUS();

        try {
            ConnectDB.getInstance().connect();
        } catch (Exception e) {
            e.printStackTrace();
        }

        th.setThuongHieuID(sanPham_BUS.getIdThuongHieuByName(th.getTenThuongHieu()));

        if (th.getThuongHieuID() == -1) {
            int check = JOptionPane.showConfirmDialog(null, "Tên thương hiệu này vốn chưa có sẳn. Tạo mới?");
            if (check == 0) {
                ThuongHieu_BUS thuongHieu_BUS = new ThuongHieu_BUS();
                thuongHieu_BUS.addThuongHieu(th);
                th.setThuongHieuID(sanPham_BUS.getIdThuongHieuByName(th.getTenThuongHieu()));
            }
        }

        ncc.setNhaCungCapID(sanPham_BUS.getIdNhaCungCapByName(ncc.getTenNhaCungCap()));

        if (ncc.getNhaCungCapID().equals("")) {
            int check = JOptionPane.showConfirmDialog(null, "Nhà cung cấp này vốn chưa có sẳn. Tạo mới?");
            if (check == 0) {
                NhaCungCap_BUS nhaCungCap_BUS = new NhaCungCap_BUS();
                nhaCungCap_BUS.addNhaCungCap(ncc);
                ncc.setNhaCungCapID(sanPham_BUS.getIdNhaCungCapByName(ncc.getTenNhaCungCap()));
            }
        }

        SanPham sanPham = new SanPham();
        try {
            sanPham.setTenSanPham(tenSanPham);
            sanPham.setSoLuongTon(soLuongTon);
            sanPham.setBarcode(barcode);
            sanPham.setGiaNhap(giaNhap);
            sanPham.setThue(thue);
            sanPham.setNamSanXuat(namSanXuat);
            sanPham.setXuatXu(xuatXu);
            sanPham.setLoaiDoiTra(loaiDoiTra.equalsIgnoreCase("Được đổi trả") ? "DUOC_DOI_TRA" : "KHONG_DOI_TRA");
            sanPham.setNgayNhap(DATE);
            sanPham.setImgPath(partialPath);
            sanPham.setThuongHieu(th);
            sanPham.setTacGia(new TacGia(1));
            sanPham.setTheLoai(new TheLoai(1));
            sanPham.setDanhMuc(new DanhMuc(1));
            sanPham.setNhaXuatBan(new NhaXuatBan(1));
            sanPham.setNhaCungCap(ncc);
            sanPham.setKichThuoc("");
            sanPham.setNgonNgu("");
            sanPham.setSoTrang(1);
            sanPham.setLoaiBia("");
            sanPham.setDonViDoLuong("");
        } catch (Exception ex) {

            ex.printStackTrace();
        }
        return sanPham;
    }

    public void setSanPhamSach(SanPham x) {
    
        SanPham_BUS sanPham_BUS = new SanPham_BUS();
        ID = x.getSanPhamID();
        try {
            ImageIcon imageIcon = new ImageIcon("src/" + x.getImgPath()); // load the image to a imageIcon

            Image image = imageIcon.getImage(); // transform it 
            Image newimg = image.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
            imageIcon = new ImageIcon(newimg);
            this.jLabel_Img.setIcon(imageIcon);
        } catch (Exception e) {
            this.jLabel_Img.setText("NO IMAGE");
        }

        this.jTextField_TenSanPham.setText(x.getTenSanPham());
        this.jTextField_SoLuongTon.setText(x.getSoLuongTon() + "");
        this.jTextField_ThuongHieu.setText(sanPham_BUS.getNameThuongHieuByID(x.getThuongHieu().getThuongHieuID()));

        this.jTextField_Barcode.setText(x.getBarcode());
        this.jTextField_NhaCungCap.setText(x.getNhaCungCap().getTenNhaCungCap());
        this.jTextField_GiaNhap.setText(x.getGiaNhap() + "");
        this.jTextField_Thue.setText(x.getThue() + "");
        this.jTextField1_NamSanXuat.setText(x.getNamSanXuat() + "");

        this.jTextField_XuatXu.setText(x.getXuatXu());
        this.jTextField_NhaCungCap.setText(sanPham_BUS.getNameNhaCungCapByID(x.getNhaCungCap().getNhaCungCapID()));

        if (x.getLoaiDoiTra().equals("DUOC_DOI_TRA")) {
            this.jComboBox_LoaiDoiTra.setSelectedIndex(0);
        }
        if (x.getLoaiDoiTra().equals("KHONG_DOI_TRA")) {
            this.jComboBox_LoaiDoiTra.setSelectedIndex(1);
        }
        this.txtNgay.setDate(x.getNgayNhap());
        

    }

    /**
     * @param args the command line arguments
     */
    public void disVisibleForLuu() {
        this.jButton_Sua.setBackground(new Color(204, 204, 204));
        this.jButton_Sua.setEnabled(false);
        this.jButton_Luu.setEnabled(true);
        this.jButton_Luu.setBackground(new Color(15, 145, 239));

    }

    public void disVisibleForSua() {
        this.jButton_Luu.setBackground(new Color(204, 204, 204));
        this.jButton_Luu.setEnabled(false);
        this.jButton_Sua.setEnabled(true);
        this.jButton_Sua.setBackground(new Color(15, 145, 239));

    }

    private int ID;
    private File file;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox_NCC;
    private javax.swing.JComboBox<String> comboBox_TH;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler22;
    private javax.swing.Box.Filler filler23;
    private javax.swing.Box.Filler filler24;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler26;
    private javax.swing.Box.Filler filler27;
    private javax.swing.Box.Filler filler28;
    private javax.swing.Box.Filler filler29;
    private javax.swing.Box.Filler filler30;
    private javax.swing.Box.Filler filler31;
    private javax.swing.Box.Filler filler32;
    private javax.swing.Box.Filler filler33;
    private javax.swing.Box.Filler filler34;
    private javax.swing.Box.Filler filler35;
    private javax.swing.Box.Filler filler37;
    private javax.swing.Box.Filler filler40;
    private javax.swing.Box.Filler filler41;
    private javax.swing.Box.Filler filler43;
    private javax.swing.Box.Filler filler45;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_Huy;
    private javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JComboBox<String> jComboBox_LoaiDoiTra;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_Barcode;
    private javax.swing.JLabel jLabel_GiaNhap;
    private javax.swing.JLabel jLabel_Img;
    private javax.swing.JLabel jLabel_NamSanXuat;
    private javax.swing.JLabel jLabel_NgayNhap1;
    private javax.swing.JLabel jLabel_NhaCungCap;
    private javax.swing.JLabel jLabel_SoLuongTon;
    private javax.swing.JLabel jLabel_SoTrang2;
    private javax.swing.JLabel jLabel_TacGia;
    private javax.swing.JLabel jLabel_Thue1;
    private javax.swing.JLabel jLabel_Warning;
    private javax.swing.JLabel jLabel_XuatXu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_CBB_NhaCungCap;
    private javax.swing.JPanel jPanel_CBB_ThuongHieu;
    private javax.swing.JTextField jTextField1_NamSanXuat;
    private javax.swing.JTextField jTextField_Barcode;
    private javax.swing.JTextField jTextField_GiaNhap;
    private javax.swing.JTextField jTextField_NhaCungCap;
    private javax.swing.JTextField jTextField_SoLuongTon;
    private javax.swing.JTextField jTextField_TenSanPham;
    private javax.swing.JTextField jTextField_Thue;
    private javax.swing.JTextField jTextField_ThuongHieu;
    private javax.swing.JTextField jTextField_XuatXu;
    private com.toedter.calendar.JDateChooser txtNgay;
    // End of variables declaration//GEN-END:variables
}
